# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Times',
            new_name='WorkTimes',
        ),
    ]
