# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_control', '0002_auto_20170905_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkTimes',
            new_name='WorkTime',
        ),
    ]
