# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_control', '0003_auto_20170905_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
