# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_control', '0005_auto_20170905_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='start'),
        ),
    ]
